import { useState } from 'react'

const REPORT_SECTIONS = [
  { label: 'Customer Insights',    color: '#f59e0b' },
  { label: 'Market Analysis',      color: '#3b82f6' },
  { label: 'Feature Priorities',   color: '#8b5cf6' },
  { label: 'SWOT Analysis',        color: '#10b981' },
  { label: 'Executive Summary',    color: '#6366f1' },
]

export default function Report({ backend }) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const download = async () => {
    setLoading(true)
    setError('')
    try {
      const response = await fetch(backend + '/report/pdf')
      if (!response.ok) {
        const json = await response.json()
        setError(json.error || json.detail || 'Failed to generate PDF')
        setLoading(false)
        return
      }
      const blob = await response.blob()
      const url = URL.createObjectURL(blob)
      const anchor = document.createElement('a')
      anchor.href = url
      anchor.download = 'product_strategy_report.pdf'
      anchor.click()
      URL.revokeObjectURL(url)
    } catch (err) {
      setError(err.message || 'An unexpected error occurred')
    }
    setLoading(false)
  }

  return (
    <div className="report-page">
      <div className="report-card">
        <div className="report-icon-wrap">
          <div className="report-icon-inner">
            <div className="report-line" style={{ width: '28px' }} />
            <div className="report-line" style={{ width: '20px' }} />
            <div className="report-line" style={{ width: '24px' }} />
            <div className="report-line" style={{ width: '16px' }} />
          </div>
        </div>
        <h2>Executive Strategy Report</h2>
        <p>Download a comprehensive PDF containing all 5 analysis sections generated by the AI agent pipeline.</p>
        <div className="report-sections">
          {REPORT_SECTIONS.map(({ label, color }) => (
            <div key={label} className="report-section-item">
              <div className="section-dot" style={{ background: color }} />
              <span>{label}</span>
            </div>
          ))}
        </div>
        <button className="btn-primary btn-large" onClick={download} disabled={loading}>
          {loading ? 'Generating PDF...' : 'Download PDF Report'}
        </button>
        {error && <p className="error-msg">{error}</p>}
      </div>
    </div>
  )
}
